### ISSUE TITLE
Клиент для телевизоров Samsung

### ISSUE THREAD

**Issue by negativ72rus** [KestL/soap4plex#1]
В клиенте Плекс для телевизора самсунг картинка с артефактами и очень низкого разрешения. В веб-клиенте и клиенте для Мак все прекрасно, не подскажите в чем может быть дело??

**Comment by kestl** [comment]
Раз в других клиентах все в порядке, дело, видимо, в настройках перекодировки клиента на телевизоре. Надо смотреть опции, там должна быть настройка битрейта/качества. То есть это не связано с плагином, смотрите настройки самого клиента Plex
