### ISSUE TITLE
В доступе отказано

### ISSUE THREAD

**Issue by YoriRikunagi** [KestL/soap4plex#10]
При попытке посмотреть список сериалов в веб-версии PLEX или со SMART-TV,выводится сообщение: "В доступе отказано."  Как решить данную проблему?

**Comment by kestl** [comment]
Лог com.plexapp.plugins.soap4me.log мне пришлите, может там что найду. Но, вообще говоря, странная проблема. Что делали перед тем, как появилась? Обновляли плекс?

**Comment by YoriRikunagi** [comment]
Скачал plex с оф.сайта. Только поставил плагин и всё.

[com.plexapp.plugins.soap4me.txt](https://github.com/KestL/soap4plex/files/455585/com.plexapp.plugins.soap4me.txt)

**Comment by kestl** [comment]
А в настройки зашли и залогинились?

**Comment by YoriRikunagi** [comment]
Конечно. И оплатил подписку на месяц.

**Comment by kestl** [comment]
А какая версия плекса сервера?

**Comment by YoriRikunagi** [comment]
1.1.3.2700

**Comment by kestl** [comment]
Обновился, у меня продолжает работать. А другие плагины работают?

**Comment by YoriRikunagi** [comment]
Скачал плагин никилодиона - работает.

**Comment by kestl** [comment]
Повторите тогда баг и еще раз выложите логи, только кроме уже указанного, еще com.plexapp.system.log и Plex Media Server.log. Или просто всю папку заархивируйте и выложите

**Comment by kestl** [comment]
В поле логина надо вводить ЛОГИН, а не почту

**Comment by YoriRikunagi** [comment]
Да,действительно тупанул) Извините за беспокойство)
