### ISSUE TITLE
Plex Home Theater

### ISSUE THREAD

**Issue by alexanry** [KestL/soap4plex#2]
Не работает в новой версии Plex Home Theater. Постоянно выдает ошибку, что невозможно проиграть файл

**Comment by kestl** [comment]
Судя по всему, это баг именно свежей версии Plex Home Theater. Есть какие-нибудь каналы, которые нормально работают?

**Comment by alexanry** [comment]
The Daily Show работает

**Comment by alexanry** [comment]
А какая версия Plex Home Theater точно работает? Как временное решение...

**Comment by alexanry** [comment]
Проверил Home Theater версии 1.4.1, 1.3.5, 1.2.3  - не работает плагин.

Update: соврал, 1.3.5 заработал
